// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rshpoqgrqystqvtsivyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzaHBvcWdycXlzdHF2dHNpdnljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MTk3MjEsImV4cCI6MjA3MzI5NTcyMX0.zSANMzP0WZC6_6xwBvRKN8OaNnC1strU3u12uqq1jQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});