// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kiphraxjvfpaudssawjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpcGhyYXhqdmZwYXVkc3Nhd2poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MTkzMTIsImV4cCI6MjA3MzI5NTMxMn0.3Mjg0ffsNltXMaR2CEKiqi9oCLGO9Y1V2VP2xv3_Pts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});